REQUEST_STARTDRILLING = "startDrilling"
REQUEST_RELOADDATA = "reloadData"
REQUEST_DRIVEX1 = "driveToX1"
REQUEST_DRIVEX2 = "driveToX2"
REQUEST_DRIVEX3 = "driveToX3"

RESPONSE_SUCCESS = "success"
RESPONSE_FAIL = "fail"

INTERRUPT = "interrupt"

INVALID_REQUEST = "invalidRequest"
